'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var lr = require('@lezer/lr');
var language = require('@codemirror/language');
var highlight = require('@lezer/highlight');
var common = require('@lezer/common');

// This file was generated by lezer-generator. You probably shouldn't edit it.
const parser = lr.LRParser.deserialize({
  version: 14,
  states: "%jQYQPOOO_QPO'#C_OOQO'#Ci'#CiQYQPOOOdQQO'#CaOOQO'#Cj'#CjOrQPO,58yOOQO-E6g-E6gOOQO'#Cb'#CbO}QPO,58{OOQO-E6h-E6hO!SQSO1G.gO!bQPO'#CgOOQO'#Cf'#CfO!gQSO'#CfOdQQO'#CdOOQO'#Cd'#CdO!lQPO7+$RO!qQWO,59RO!yQPO,59QO#RQPO,59OO#WQPO<<GmO#]QPO1G.mO!gQSO'#CkO#bQPO1G.lOOQO1G.l1G.lO#jQ`O1G.jOOQOAN=XAN=XOOQO7+$X7+$XOOQO,59V,59VOOQO-E6i-E6iOOQO7+$W7+$WOOQO'#Ce'#CeO#uQPO7+$UOOQO<<Gp<<Gp",
  stateData: "#z~ObOSPOS~OSPO~OcSO~OVWOdWOeWOfWO~OcSOSRa`Ra~OgZO~O[[Oh_Oo]Op^O~OhbO~O[[O~OieO~OVfOnfO~OigOqiO~OijO~OSkO~OmlO~OigOqoO~OjpOkpOlpO~OmrO~O",
  goto: "!e`PPPaPeiPoruxP!R!X!_TQORTTPUQXSRd_RaZRqjR`ZQ]ZQc^RmgQRORVRQUPRYUQhcRnh",
  nodeNames: "⚠ Comment File State Sname State_rule Tape_symbol Var_name Tape_action Head_move Fun_sequence Function Fun_name",
  maxTerm: 33,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: ")_~RkXY!vYZ!v]^!vpq!vxy#Xyz#^|}#c}!O#h!P!Q#s!Q!R$b!R!S$g!S![$n!c!n$s!n!o&c!o!t$s!t!u&z!u!v'c!v!}$s!}#O'z#P#Q(X#R#S(^#T#o&O#p#q(q$Jb'&l(v;(b;(c({;(c;(d)R;(d;(e)X~!{Sb~XY!vYZ!v]^!vpq!v~#^Oh~~#cOm~~#hOi~~#kP!`!a#n~#sOg~~#vP!P!Q#y~$OSP~OY#yZ;'S#y;'S;=`$[<%lO#y~$_P;=`<%l#y~$gOd~Y$nOeQnWW$sOnW_$|S[SSPVY!R![$s!c!}$s#R#S%Y#T#o&OT%aS[SSP!R![%Y!c!}%Y#R#S%Y#T#o%mP%rSSP!R![%m!c!}%m#R#S%m#T#o%mZ&VSSPVY!R![&O!c!}&O#R#S%m#T#o&Oo&nSj`[SSPVY!R![$s!c!}$s#R#S%Y#T#o&Oo'VSk`[SSPVY!R![$s!c!}$s#R#S%Y#T#o&Oo'nSl`[SSPVY!R![$s!c!}$s#R#S%Y#T#o&O~(PPp~#P#Q(S~(XOo~~(^Oq~R(eSfQSP!R![%m!c!}%m#R#S%m#T#o%m~(vOc~P({OSPP)OP;=d<%l(vP)UP;=`<%l(vP)[P;=`;My(v",
  tokenizers: [0, 1, 2, 3, 4],
  topRules: {"File":[0,2]},
  tokenPrec: 0
});

const TURNIPLang = language.LRLanguage.define({
    parser: parser.configure({
        props: [
            language.indentNodeProp.add({
                Application: language.delimitedIndent({ closing: ")", align: false }),
            }),
            language.foldNodeProp.add({
                Application: language.foldInside,
            }),
            highlight.styleTags({
                Tape_symbol: highlight.tags.literal,
                Head_move: highlight.tags.typeName,
                //Tape_action: t.
                //State_rule: t.
                //State: t.
                Sname: highlight.tags.variableName,
                Comment: highlight.tags.comment,
                "->": highlight.tags.operator,
                "|": highlight.tags.operator,
                "( )": highlight.tags.paren,
                ",": highlight.tags.operator,
            }),
        ],
    }),
    languageData: {
        commentTokens: { line: "#" },
    },
});
// TODO: we may want use cache
// See https://github.com/codemirror/lang-python/blob/main/src/complete.ts#L61
/**
 * Construct a completions list containing all defined states.
 * @param tree
 * @param doc
 * @param excludedFrom position of the current node, we don't want to include the partially written state in the completion list
 * @returns
 */
function getStateNames(tree, doc, excludedFrom) {
    const names = new Set();
    tree.cursor(common.IterMode.IncludeAnonymous).iterate((node) => {
        if (node.type.is("Sname") && node.from !== excludedFrom) {
            names.add(doc.sliceString(node.from, node.to));
        }
    });
    let completions = [
        { label: "START", type: "constant" },
        { label: "END", type: "constant" },
    ];
    for (const name of names) {
        if (name !== "START" && name !== "END") {
            completions.push({ label: name, type: "variable" });
        }
    }
    return completions;
}
function turnipCompletionFor(context) {
    let { state, pos } = context;
    let tree = language.syntaxTree(state).resolveInner(pos, -1);
    //let around = tree.resolve(pos)
    // tree.from correspond to the start of the current node
    const stateNames = getStateNames(language.syntaxTree(state), state.doc, tree.from);
    // TODO: we may want to propose Sname autocomplete even when a Sname is not started, but only expected
    if (tree.name == "Sname") {
        return {
            from: tree.from,
            options: stateNames,
        };
    }
    // TODO: we may want to autocomplete complete states
}
const turnipCompletion = TURNIPLang.data.of({
    autocomplete: turnipCompletionFor,
});
function turnip_lang() {
    return new language.LanguageSupport(TURNIPLang, [turnipCompletion]);
}

exports.TURNIPLang = TURNIPLang;
exports.turnipCompletion = turnipCompletion;
exports.turnip_lang = turnip_lang;
